// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Asztalfoglalás', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Asztalfoglalás', async function() {
    await driver.get("http://localhost:3001/")
    await driver.manage().window().setRect({ width: 2576, height: 1416 })
    await driver.findElement(By.linkText("Asztalfoglalás")).click()
    await driver.findElement(By.name("name")).click()
    await driver.findElement(By.name("name")).sendKeys("Horváth Béla")
    await driver.findElement(By.name("phone_number")).click()
    await driver.findElement(By.name("phone_number")).sendKeys("06306005364")
    await driver.findElement(By.name("date")).click()
    await driver.findElement(By.name("date")).sendKeys("2025-04-18")
    await driver.findElement(By.name("time")).click()
    {
      const dropdown = await driver.findElement(By.name("time"))
      await dropdown.findElement(By.xpath("//option[. = '18:00']")).click()
    }
    await driver.findElement(By.css(".mb-3:nth-child(1) option:nth-child(4)")).click()
    await driver.findElement(By.name("guests")).click()
    {
      const dropdown = await driver.findElement(By.name("guests"))
      await dropdown.findElement(By.xpath("//option[. = '3 fő']")).click()
    }
    await driver.findElement(By.css(".mb-3:nth-child(3) option:nth-child(4)")).click()
    {
      const element = await driver.findElement(By.name("special_requests"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("special_requests"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("special_requests"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("special_requests")).click()
    await driver.findElement(By.name("special_requests")).sendKeys("asd")
    await driver.findElement(By.css(".btn-gold")).click()
  })
})
