// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Bejelentkezes', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Bejelentkezes', async function() {
    await driver.get("http://localhost:3001/")
    await driver.manage().window().setRect({ width: 1674, height: 1378 })
    await driver.findElement(By.css(".nav-item:nth-child(5) > .nav-link")).click()
    await driver.findElement(By.name("email")).click()
  })
})
