// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Regisztracio', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Regisztracio', async function() {
    await driver.get("http://localhost:3001/")
    await driver.manage().window().setRect({ width: 1674, height: 1378 })
    await driver.findElement(By.css(".nav-item:nth-child(5) > .nav-link")).click()
    await driver.findElement(By.linkText("Regisztrálj")).click()
    await driver.findElement(By.name("first_name")).click()
    await driver.findElement(By.name("first_name")).sendKeys("Horvath")
    await driver.findElement(By.name("last_name")).click()
    await driver.findElement(By.name("last_name")).sendKeys("Béla")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("Horv.Bela@gmail.com")
    await driver.findElement(By.name("phone")).click()
    await driver.findElement(By.name("phone")).sendKeys("06306005364")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("Selinium01")
    await driver.findElement(By.name("confirmPassword")).click()
    await driver.findElement(By.name("confirmPassword")).click()
    await driver.findElement(By.name("confirmPassword")).sendKeys("Selinium01")
    await driver.findElement(By.css(".btn-gold")).click()
    assert(await driver.switchTo().alert().getText() == "Sikeres regisztráció!")
  })
})
