// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Szobafoglalás', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Szobafoglalás', async function() {
    await driver.get("http://localhost:3001/")
    await driver.manage().window().setRect({ width: 2576, height: 1416 })
    await driver.findElement(By.linkText("Szobafoglalás")).click()
    await driver.findElement(By.name("user_name")).click()
    await driver.findElement(By.name("user_name")).sendKeys("Horváth Béla")
    await driver.findElement(By.name("user_email")).click()
    await driver.findElement(By.name("user_email")).sendKeys("H.Bela@gmail.com")
    await driver.findElement(By.name("phone_number")).click()
    await driver.findElement(By.name("phone_number")).sendKeys("06306005364")
    await driver.findElement(By.name("check_in")).click()
    await driver.findElement(By.name("check_in")).click()
    await driver.findElement(By.name("check_in")).sendKeys("2025-04-14")
    await driver.findElement(By.name("check_out")).click()
    await driver.findElement(By.name("check_out")).sendKeys("2025-04-18")
    await driver.findElement(By.name("guests")).click()
    {
      const dropdown = await driver.findElement(By.name("guests"))
      await dropdown.findElement(By.xpath("//option[. = '3 fő']")).click()
    }
    await driver.findElement(By.css(".col-md-6:nth-child(1) option:nth-child(4)")).click()
    await driver.findElement(By.name("pay_method")).click()
    {
      const dropdown = await driver.findElement(By.name("pay_method"))
      await dropdown.findElement(By.xpath("//option[. = 'Banki átutalás']")).click()
    }
    await driver.findElement(By.css(".col-md-6:nth-child(2) option:nth-child(3)")).click()
    await driver.findElement(By.name("room_id")).click()
    {
      const dropdown = await driver.findElement(By.name("room_id"))
      await dropdown.findElement(By.xpath("//option[. = 'Luxus Suite - 54000 Ft/éj']")).click()
    }
    await driver.findElement(By.css(".mb-3:nth-child(5) option:nth-child(2)")).click()
    await driver.findElement(By.name("special_requests")).click()
    await driver.findElement(By.name("special_requests")).sendKeys("asd")
    await driver.findElement(By.name("additional_services")).click()
    await driver.findElement(By.name("additional_services")).sendKeys("asd")
    await driver.findElement(By.css(".btn-gold")).click()
  })
})
